openapi: 3.0.0
info:
    title: Micro Service API
    version: 1.0.0
servers:
    - url: data_fetcher:5000
    - url: data_manager:5001
    - url: job_runner:5002
paths:
    /api/internal/data_fetcher/download:
        post:
            summary: called by job runner to strat downloading data from planetAPI
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                user_id:
                                    type: string
                                project_id:
                                    type: string
                                job_id:
                                    type: string
                                    description: The job id is created everytime a user presses start
                                start_date:
                                    type: string
                                    format: date
                                end_date:
                                    type: string
                                    format: date
                                aoi_array:
                                    type: array
                                    items:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                x:
                                                    type: number
                                                y:
                                                    type: number
                                cloud_cover:
                                    type: number
                                PLANET_API_KEY:
                                    type: string
            responses:
                200:
                    description: Successful download
                400:
                    description: Bad request

    /api/internal/data_fetcher/stop:
        get:
            summary: To stop the running download job
            responses:
                200:
                    description: Successful stop
                400:
                    description: job does not exist

    /api/internal/data_manager/add_tif:
        post:
            summary: Add files to sftp
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                user_id:
                                    type: string
                                project_id:
                                    type: string
                                image_id:
                                    type: string
                                image:
                                    type: string
                                transform:
                                    type: object
                                    properties:
                                        x_coord:
                                            type: number
                                        y_coord:
                                            type: number
                                        x_meter:
                                            type: number
                                        y_meter:
                                            type: number
                                        x_rotation:
                                            type: number
                                        y_rotation:
                                            type: number

                                
            responses:
                200:
                    description: Successful Added
                400:
                    description: Bad request

    /api/internal/data_manager/user/add:
        post:
            summary: Add a new user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                password:
                                    type: string
                                name:
                                    type: string
                                PLANET_API_KEY:
                                    type: string
            responses:
                '200':
                    description: User added successfully
                '400':
                    description: User was not added

    /api/internal/data_manager/user/verify:
        post:
            summary: Verify user credentials
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                password:
                                    type: string
            responses:
                '200':
                    description: User verified successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    _id:
                                        type: string
                                    email:
                                        type: string
                                    name:
                                        type: string
                '400':
                    description: User verification failed

    /api/internal/data_manager/project/get:
        get:
            summary: Get user projects
            parameters:
                - in: header
                  name: user_id
                  required: true
                  schema:
                    type: string
            responses:
                '200':
                    description: Projects retrieved successfully
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                '400':
                    description: Failed to retrieve projects

    /api/internal/data_manager/project/add:
        post:
            summary: Add a new project
            parameters:
                - in: header
                  name: user_id
                  required: true
                  schema:
                    type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                farm_name:
                                    type: string
                                aoi:
                                    type: array
                                    items:
                                        type: array
                                        items:
                                            type: number
                                crop:
                                    type: string
                                created_at:
                                    type: string
            responses:
                '200':
                    description: Project added successfully
                '400':
                    description: Failed to add project

    /api/internal/data_manager/image/get:
        post:
            summary: Get image for a project
            parameters:
                - in: header
                  name: user_id
                  required: true
                  schema:
                    type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                project_id:
                                    type: string
                                start_date:
                                    type: string
                                end_date:
                                    type: string
            responses:
                '200':
                    description: Image retrieved successfully
                '400':
                    description: Failed to retrieve image

    /api/external/auth/signup:
        post:
            summary: Sign up a new user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                password:
                                    type: string
                                name:
                                    type: string
                                PLANET_API_KEY:
                                    type: string
            responses:
                '200':
                    description: User added successfully
                '400':
                    description: User was not added

    /api/external/auth/login:
        post:
            summary: User login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                password:
                                    type: string
            responses:
                '200':
                    description: User logged in successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    user:
                                        type: object
                                        properties:
                                            _id:
                                                type: string
                                            email:
                                                type: string
                                            name:
                                                type: string
                                    token:
                                        type: string
                                    expires_in:
                                        type: integer
                '400':
                    description: Login failed

    /api/external/projects:
        get:
            summary: Get user projects
            parameters:
                - in: header
                  name: authorization
                  required: true
                  schema:
                      type: string
                - in: header
                  name: user_id
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Projects retrieved successfully
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                '400':
                    description: Failed to retrieve projects
        post:
            summary: Add a new project
            parameters:
                - in: header
                  name: authorization
                  required: true
                  schema:
                      type: string
                - in: header
                  name: user_id
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                farm_name:
                                    type: string
                                aoi:
                                    type: array
                                    items:
                                        type: array
                                        items:
                                            type: number
                                crop:
                                    type: string
                                created_at:
                                    type: string
            responses:
                '200':
                    description: Project added successfully
                '400':
                    description: Failed to add project

    /api/external/projects/{project_id}/image:
        post:
            summary: Get image for a project
            parameters:
                - in: path
                  name: project_id
                  required: true
                  schema:
                      type: string
                - in: header
                  name: authorization
                  required: true
                  schema:
                      type: string
                - in: header
                  name: user_id
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                start_date:
                                    type: string
                                end_date:
                                    type: string
            responses:
                '200':
                    description: Image retrieved successfully
                '400':
                    description: Failed to retrieve image