FROM python:3.10-slim

RUN pip install --upgrade pip
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
RUN pip install debugpy
WORKDIR /app
COPY ./app /app

CMD ["python3", "-m", "debugpy", "--listen", "0.0.0.0:5678", "app.py"]
