FROM python:3.10-slim

COPY ./app /app
COPY ./requirements.txt /requirements.txt
WORKDIR /

RUN apt-get update
RUN pip3 install -r requirements.txt
RUN pip install debugpy

CMD ["python3", "-m", "debugpy", "--listen", "0.0.0.0:5678", "app/main.py"]