version: '3.0'

services:
  mongo:
    image: mongo:8
    container_name: mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - internal
      - test_cyp_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  mongo_express:
    image: mongo-express:latest
    container_name: mongo_express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - "8081:8081"
    networks:
      - internal
      - test_cyp_network
    depends_on:
      - mongo

  
  sftp:
    image: atmoz/sftp
    container_name: sftp
    volumes:
      - ./data/sftp:/home/sftp/upload
    ports:
      - 22:22
    networks:
      - internal
      - test_cyp_network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 1G
    command: sftp:Sftp@12345:1002:12345:./upload

networks:
  internal:
    name: cyp_data_manager_network
    external: true
  test_cyp_network:
    name: test_cyp_network
    external: true

